name: UnsafeEnchantments
main: me.mastergabemod.unsafeenchantfix.Main
version: 1.5
api-version: 1.20
author: MasterGabeMOD
commands:
  unsafecheck:
    description: Manually check an item for unsafe enchantments
    usage: /unsafecheck
    permission: unsafecheck.admin
