checks:
  enable_checks: true
  check_inventory: true
  check_potions: true
  clear_unsafe_enchantments: true
  max_enchantment_level: 5
  
  # Potion checks
  potion_checks: 
    allowed_effects: 
      - HEAL
      - REGENERATION
      - SPEED
      - INCREASE_DAMAGE
      - STRENGTH
      - NIGHT_VISION
    max_effect_amplifier: 3 
    max_effect_duration_ticks: 6000 
  
  # Firework checks
  check_fireworks: true
  firework_checks:
    max_flight_duration: 3  # Max allowed flight duration for fireworks (1-3)
    allowed_effects:
      - BALL
      - STAR
      - BURST

  # Sign checks
  check_crash_signs: true
  sign_checks:
    max_line_length: 100 # Maximum length of a single line on a sign
    invalid_pattern: "[^\\x20-\\x7E]" 
  
  # Book checks
  check_crash_books: true
  book_checks:
    max_pages: 50 # Maximum number of pages allowed in a book
    max_page_length: 2560 # Maximum number of characters per page
    invalid_pattern: "[^\\x20-\\x7E]" 

  # Container checks
  check_crash_chests: true
  container_checks:
    max_item_stack_size: 64
    max_custom_model_data: 1000

task_settings:
  task_delay_seconds: 5 
  task_period_seconds: 5
